# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from backend.grpc import trade_pb2 as trade__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trade_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradeServiceStub(object):
    """============================================================
    量化交易系统 gRPC 协议

    策略引擎 (客户端) ←→ 交易引擎 (服务端)
    策略引擎不感知底层是真实交易还是模拟交易
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlaceOrder = channel.unary_unary(
                '/xtquant.TradeService/PlaceOrder',
                request_serializer=trade__pb2.OrderRequest.SerializeToString,
                response_deserializer=trade__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/xtquant.TradeService/CancelOrder',
                request_serializer=trade__pb2.CancelRequest.SerializeToString,
                response_deserializer=trade__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.GetAccount = channel.unary_unary(
                '/xtquant.TradeService/GetAccount',
                request_serializer=trade__pb2.AccountRequest.SerializeToString,
                response_deserializer=trade__pb2.AccountResponse.FromString,
                _registered_method=True)
        self.GetPositions = channel.unary_unary(
                '/xtquant.TradeService/GetPositions',
                request_serializer=trade__pb2.PositionsRequest.SerializeToString,
                response_deserializer=trade__pb2.PositionsResponse.FromString,
                _registered_method=True)
        self.GetOrders = channel.unary_unary(
                '/xtquant.TradeService/GetOrders',
                request_serializer=trade__pb2.OrdersRequest.SerializeToString,
                response_deserializer=trade__pb2.OrdersResponse.FromString,
                _registered_method=True)
        self.GetTrades = channel.unary_unary(
                '/xtquant.TradeService/GetTrades',
                request_serializer=trade__pb2.TradesRequest.SerializeToString,
                response_deserializer=trade__pb2.TradesResponse.FromString,
                _registered_method=True)
        self.SubscribeMarketData = channel.unary_stream(
                '/xtquant.TradeService/SubscribeMarketData',
                request_serializer=trade__pb2.MarketDataRequest.SerializeToString,
                response_deserializer=trade__pb2.MarketDataTick.FromString,
                _registered_method=True)
        self.GetHistoryKline = channel.unary_unary(
                '/xtquant.TradeService/GetHistoryKline',
                request_serializer=trade__pb2.KlineRequest.SerializeToString,
                response_deserializer=trade__pb2.KlineResponse.FromString,
                _registered_method=True)
        self.GetStockList = channel.unary_unary(
                '/xtquant.TradeService/GetStockList',
                request_serializer=trade__pb2.StockListRequest.SerializeToString,
                response_deserializer=trade__pb2.StockListResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/xtquant.TradeService/Ping',
                request_serializer=trade__pb2.PingRequest.SerializeToString,
                response_deserializer=trade__pb2.PingResponse.FromString,
                _registered_method=True)
        self.GetTradeMode = channel.unary_unary(
                '/xtquant.TradeService/GetTradeMode',
                request_serializer=trade__pb2.TradeModeRequest.SerializeToString,
                response_deserializer=trade__pb2.TradeModeResponse.FromString,
                _registered_method=True)


class TradeServiceServicer(object):
    """============================================================
    量化交易系统 gRPC 协议

    策略引擎 (客户端) ←→ 交易引擎 (服务端)
    策略引擎不感知底层是真实交易还是模拟交易
    ============================================================

    """

    def PlaceOrder(self, request, context):
        """下单
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """撤单
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccount(self, request, context):
        """查询账户
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositions(self, request, context):
        """查询持仓
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrders(self, request, context):
        """查询委托
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrades(self, request, context):
        """查询今日成交
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeMarketData(self, request, context):
        """订阅实时行情 (server streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoryKline(self, request, context):
        """查询历史K线
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStockList(self, request, context):
        """获取可用股票列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """心跳
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTradeMode(self, request, context):
        """查询交易模式 (real/sim)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=trade__pb2.OrderRequest.FromString,
                    response_serializer=trade__pb2.OrderResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=trade__pb2.CancelRequest.FromString,
                    response_serializer=trade__pb2.CancelResponse.SerializeToString,
            ),
            'GetAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccount,
                    request_deserializer=trade__pb2.AccountRequest.FromString,
                    response_serializer=trade__pb2.AccountResponse.SerializeToString,
            ),
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=trade__pb2.PositionsRequest.FromString,
                    response_serializer=trade__pb2.PositionsResponse.SerializeToString,
            ),
            'GetOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrders,
                    request_deserializer=trade__pb2.OrdersRequest.FromString,
                    response_serializer=trade__pb2.OrdersResponse.SerializeToString,
            ),
            'GetTrades': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrades,
                    request_deserializer=trade__pb2.TradesRequest.FromString,
                    response_serializer=trade__pb2.TradesResponse.SerializeToString,
            ),
            'SubscribeMarketData': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeMarketData,
                    request_deserializer=trade__pb2.MarketDataRequest.FromString,
                    response_serializer=trade__pb2.MarketDataTick.SerializeToString,
            ),
            'GetHistoryKline': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistoryKline,
                    request_deserializer=trade__pb2.KlineRequest.FromString,
                    response_serializer=trade__pb2.KlineResponse.SerializeToString,
            ),
            'GetStockList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockList,
                    request_deserializer=trade__pb2.StockListRequest.FromString,
                    response_serializer=trade__pb2.StockListResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=trade__pb2.PingRequest.FromString,
                    response_serializer=trade__pb2.PingResponse.SerializeToString,
            ),
            'GetTradeMode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTradeMode,
                    request_deserializer=trade__pb2.TradeModeRequest.FromString,
                    response_serializer=trade__pb2.TradeModeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xtquant.TradeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xtquant.TradeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradeService(object):
    """============================================================
    量化交易系统 gRPC 协议

    策略引擎 (客户端) ←→ 交易引擎 (服务端)
    策略引擎不感知底层是真实交易还是模拟交易
    ============================================================

    """

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.TradeService/PlaceOrder',
            trade__pb2.OrderRequest.SerializeToString,
            trade__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.TradeService/CancelOrder',
            trade__pb2.CancelRequest.SerializeToString,
            trade__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.TradeService/GetAccount',
            trade__pb2.AccountRequest.SerializeToString,
            trade__pb2.AccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.TradeService/GetPositions',
            trade__pb2.PositionsRequest.SerializeToString,
            trade__pb2.PositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.TradeService/GetOrders',
            trade__pb2.OrdersRequest.SerializeToString,
            trade__pb2.OrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.TradeService/GetTrades',
            trade__pb2.TradesRequest.SerializeToString,
            trade__pb2.TradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xtquant.TradeService/SubscribeMarketData',
            trade__pb2.MarketDataRequest.SerializeToString,
            trade__pb2.MarketDataTick.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistoryKline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.TradeService/GetHistoryKline',
            trade__pb2.KlineRequest.SerializeToString,
            trade__pb2.KlineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStockList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.TradeService/GetStockList',
            trade__pb2.StockListRequest.SerializeToString,
            trade__pb2.StockListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.TradeService/Ping',
            trade__pb2.PingRequest.SerializeToString,
            trade__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTradeMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.TradeService/GetTradeMode',
            trade__pb2.TradeModeRequest.SerializeToString,
            trade__pb2.TradeModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
