"""initial: all tables

Revision ID: 02dc32b8dde0
Revises: 
Create Date: 2026-05-17 22:00:58.919339
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '02dc32b8dde0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_account_snapshots_time'), table_name='account_snapshots')
    op.alter_column('backtest_results', 'equity_curve',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('backtest_results', 'buy_signals',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('backtest_runs', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('backtest_runs', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('backtest_runs', 'params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_backtest_runs_strategy'), table_name='backtest_runs')
    op.drop_index(op.f('idx_positions_snapshot'), table_name='positions')
    op.alter_column('strategies', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('strategy_signals', 'indicators',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_strategy_signals_time'), table_name='strategy_signals')
    op.alter_column('system_configs', 'config_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('trade_records', 'extra',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_trade_records_mode'), table_name='trade_records')
    op.drop_index(op.f('idx_trade_records_stock'), table_name='trade_records')
    op.drop_index(op.f('idx_trade_records_strategy'), table_name='trade_records')
    op.drop_index(op.f('idx_trade_records_time'), table_name='trade_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_trade_records_time'), 'trade_records', ['trade_time'], unique=False)
    op.create_index(op.f('idx_trade_records_strategy'), 'trade_records', ['strategy_name', 'trade_time'], unique=False)
    op.create_index(op.f('idx_trade_records_stock'), 'trade_records', ['stock_code', 'trade_time'], unique=False)
    op.create_index(op.f('idx_trade_records_mode'), 'trade_records', ['trade_mode'], unique=False)
    op.alter_column('trade_records', 'extra',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('system_configs', 'config_value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_index(op.f('idx_strategy_signals_time'), 'strategy_signals', ['created_at'], unique=False)
    op.alter_column('strategy_signals', 'indicators',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('strategies', 'config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('idx_positions_snapshot'), 'positions', ['snapshot_time'], unique=False)
    op.create_index(op.f('idx_backtest_runs_strategy'), 'backtest_runs', ['strategy_name'], unique=False)
    op.alter_column('backtest_runs', 'params',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('backtest_runs', 'end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('backtest_runs', 'start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('backtest_results', 'buy_signals',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('backtest_results', 'equity_curve',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index(op.f('idx_account_snapshots_time'), 'account_snapshots', ['snapshot_time'], unique=False)
    # ### end Alembic commands ###
