"""add_backtest_v2_columns

Revision ID: a04c39e88f7f
Revises: 02dc32b8dde0
Create Date: 2026-05-25 08:19:09.152180
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a04c39e88f7f'
down_revision: Union[str, None] = '02dc32b8dde0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_results', sa.Column('xirr', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('backtest_results', sa.Column('return_on_deployed', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('backtest_results', sa.Column('drawdown_curve', sa.JSON(), nullable=True))
    op.add_column('backtest_results', sa.Column('monthly_returns', sa.JSON(), nullable=True))
    op.add_column('backtest_results', sa.Column('trades_json', sa.JSON(), nullable=True))
    op.add_column('backtest_results', sa.Column('baseline', sa.JSON(), nullable=True))
    op.drop_column('backtest_results', 'benchmark')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_results', sa.Column('benchmark', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True))
    op.drop_column('backtest_results', 'baseline')
    op.drop_column('backtest_results', 'trades_json')
    op.drop_column('backtest_results', 'monthly_returns')
    op.drop_column('backtest_results', 'drawdown_curve')
    op.drop_column('backtest_results', 'return_on_deployed')
    op.drop_column('backtest_results', 'xirr')
    # ### end Alembic commands ###
