# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import trade_service_pb2 as trade__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trade_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradeServiceStub(object):
    """交易服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuyStock = channel.unary_unary(
                '/trade.TradeService/BuyStock',
                request_serializer=trade__service__pb2.BuyRequest.SerializeToString,
                response_deserializer=trade__service__pb2.TradeResponse.FromString,
                _registered_method=True)
        self.SellStock = channel.unary_unary(
                '/trade.TradeService/SellStock',
                request_serializer=trade__service__pb2.SellRequest.SerializeToString,
                response_deserializer=trade__service__pb2.TradeResponse.FromString,
                _registered_method=True)
        self.CancelStock = channel.unary_unary(
                '/trade.TradeService/CancelStock',
                request_serializer=trade__service__pb2.CancelRequest.SerializeToString,
                response_deserializer=trade__service__pb2.TradeResponse.FromString,
                _registered_method=True)
        self.TestConnection = channel.unary_unary(
                '/trade.TradeService/TestConnection',
                request_serializer=trade__service__pb2.TestRequest.SerializeToString,
                response_deserializer=trade__service__pb2.TestResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/trade.TradeService/Shutdown',
                request_serializer=trade__service__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=trade__service__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class TradeServiceServicer(object):
    """交易服务定义
    """

    def BuyStock(self, request, context):
        """买入股票
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SellStock(self, request, context):
        """卖出股票
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelStock(self, request, context):
        """撤销股票订单
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestConnection(self, request, context):
        """测试连接
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """关闭服务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BuyStock': grpc.unary_unary_rpc_method_handler(
                    servicer.BuyStock,
                    request_deserializer=trade__service__pb2.BuyRequest.FromString,
                    response_serializer=trade__service__pb2.TradeResponse.SerializeToString,
            ),
            'SellStock': grpc.unary_unary_rpc_method_handler(
                    servicer.SellStock,
                    request_deserializer=trade__service__pb2.SellRequest.FromString,
                    response_serializer=trade__service__pb2.TradeResponse.SerializeToString,
            ),
            'CancelStock': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelStock,
                    request_deserializer=trade__service__pb2.CancelRequest.FromString,
                    response_serializer=trade__service__pb2.TradeResponse.SerializeToString,
            ),
            'TestConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.TestConnection,
                    request_deserializer=trade__service__pb2.TestRequest.FromString,
                    response_serializer=trade__service__pb2.TestResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=trade__service__pb2.ShutdownRequest.FromString,
                    response_serializer=trade__service__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trade.TradeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trade.TradeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradeService(object):
    """交易服务定义
    """

    @staticmethod
    def BuyStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trade.TradeService/BuyStock',
            trade__service__pb2.BuyRequest.SerializeToString,
            trade__service__pb2.TradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SellStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trade.TradeService/SellStock',
            trade__service__pb2.SellRequest.SerializeToString,
            trade__service__pb2.TradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trade.TradeService/CancelStock',
            trade__service__pb2.CancelRequest.SerializeToString,
            trade__service__pb2.TradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trade.TradeService/TestConnection',
            trade__service__pb2.TestRequest.SerializeToString,
            trade__service__pb2.TestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trade.TradeService/Shutdown',
            trade__service__pb2.ShutdownRequest.SerializeToString,
            trade__service__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
