# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trade_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trade_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13trade_service.proto\x12\x05trade\"?\n\nBuyRequest\x12\x12\n\nstock_code\x18\x01 \x01(\t\x12\x0e\n\x06volume\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x01\"@\n\x0bSellRequest\x12\x12\n\nstock_code\x18\x01 \x01(\t\x12\x0e\n\x06volume\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x01\"!\n\rCancelRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x03\"B\n\rTradeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x11\n\tasync_seq\x18\x03 \x01(\x03\"1\n\x0bTestRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"B\n\x0cTestResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"\x11\n\x0fShutdownRequest\"4\n\x10ShutdownResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xad\x02\n\x0cTradeService\x12\x33\n\x08\x42uyStock\x12\x11.trade.BuyRequest\x1a\x14.trade.TradeResponse\x12\x35\n\tSellStock\x12\x12.trade.SellRequest\x1a\x14.trade.TradeResponse\x12\x39\n\x0b\x43\x61ncelStock\x12\x14.trade.CancelRequest\x1a\x14.trade.TradeResponse\x12\x39\n\x0eTestConnection\x12\x12.trade.TestRequest\x1a\x13.trade.TestResponse\x12;\n\x08Shutdown\x12\x16.trade.ShutdownRequest\x1a\x17.trade.ShutdownResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trade_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUYREQUEST']._serialized_start=30
  _globals['_BUYREQUEST']._serialized_end=93
  _globals['_SELLREQUEST']._serialized_start=95
  _globals['_SELLREQUEST']._serialized_end=159
  _globals['_CANCELREQUEST']._serialized_start=161
  _globals['_CANCELREQUEST']._serialized_end=194
  _globals['_TRADERESPONSE']._serialized_start=196
  _globals['_TRADERESPONSE']._serialized_end=262
  _globals['_TESTREQUEST']._serialized_start=264
  _globals['_TESTREQUEST']._serialized_end=313
  _globals['_TESTRESPONSE']._serialized_start=315
  _globals['_TESTRESPONSE']._serialized_end=381
  _globals['_SHUTDOWNREQUEST']._serialized_start=383
  _globals['_SHUTDOWNREQUEST']._serialized_end=400
  _globals['_SHUTDOWNRESPONSE']._serialized_start=402
  _globals['_SHUTDOWNRESPONSE']._serialized_end=454
  _globals['_TRADESERVICE']._serialized_start=457
  _globals['_TRADESERVICE']._serialized_end=758
# @@protoc_insertion_point(module_scope)
